//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Core.Entity.ViewModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTC_OperationCenterEntities : DbContext
    {
        public NTC_OperationCenterEntities()
            : base("name=NTC_OperationCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DETALLE_PASES_PRODUCCION> TB_DETALLE_PASES_PRODUCCION { get; set; }
        public virtual DbSet<TB_PROYECTO> TB_PROYECTO { get; set; }
        public virtual DbSet<TB_RUTA_PASE> TB_RUTA_PASE { get; set; }
        public virtual DbSet<TB_SERVIDOR_DEV> TB_SERVIDOR_DEV { get; set; }
        public virtual DbSet<TB_TIPO_OBJ> TB_TIPO_OBJ { get; set; }
    }
}
